apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloclient-deployment
  labels:
    app: helloclient
spec:
  selector:
    matchLabels:
      app: helloclient
  replicas: 1
  template:
    metadata:
      labels:
        app: helloclient
    spec:
      containers:
        - name: helloclient
          image: deeprs/helloclient:v1.0
          ports:
            - name: helloclient
              containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: helloclient
spec:
  selector:
    app: helloclient
  ports:
    - name: http
      port: 50051
      nodePort: 30080
  type: NodePort
